# Generated by CodiumAI

import pytest

from pr_agent.algo.utils import load_yaml, try_fix_yaml
from pr_agent.log import get_logger


class TestTryFixYaml:

    # The function successfully parses a valid YAML string.
    def test_valid_yaml(self):
        review_text = "key: value\n"
        expected_output = {"key": "value"}
        assert try_fix_yaml(review_text) == expected_output

    # The function adds '|-' to 'relevant line:' if it is not already present and successfully parses the YAML string.
    def test_add_relevant_line(self):
        review_text = "relevant line: value: 3\n"
        expected_output = {'relevant line': 'value: 3\n'}
        assert try_fix_yaml(review_text) == expected_output

    # The function extracts YAML snippet
    def test_extract_snippet(self):
        review_text1 = '''\
Here is the answer in YAML format:

```yaml
name: John Smith
age: 35
```
'''
        review_text2 = '''\
Here is the answer in YAML format:

```yml
name: John Smith
age: 35
```
'''
        review_text3 = '''\
Here is the answer in YAML format:

```
name: John Smith
age: 35
```
'''
        expected_output = {'name': 'John Smith', 'age': 35}
        assert try_fix_yaml(review_text1) == expected_output
        assert try_fix_yaml(review_text2) == expected_output
        assert try_fix_yaml(review_text3) == expected_output

    def test_first_key_extraction_preserves_key_name(self):
        response_text = (
            "{\n"
            "Some garbage: [unclosed\n\n"
            "analysis:\n"
            "  details:\n"
            "    summary: example\n"
            "issue:\n"
            "  id: 1\n\n"
            "Trailing: ???\n"
        )

        result = try_fix_yaml(response_text, first_key="analysis", last_key="issue")

        assert result == {
            "analysis": {"details": {"summary": "example"}},
            "issue": {"id": 1},
        }

    @pytest.mark.parametrize("value", ["general", "security", "maintainability"])
    def test_last_value_extraction_preserves_scalar(self, value):
        response_text = (
            "{\n"
            "Some garbage: [unclosed\n\n"
            "review:\n"
            "  summary: example\n"
            f"label: {value}\n"
        )

        result = try_fix_yaml(response_text, first_key="review", last_key="label")

        assert result == {
            "review": {"summary": "example"},
            "label": value,
        }

    @pytest.mark.parametrize("backtick_count", [1, 2, 3, 4, 6])
    def test_key_extraction_accepts_trailing_backtick_runs(self, backtick_count):
        response_text = (
            "{\n"
            "Some garbage: [unclosed\n\n"
            "review:\n"
            "  summary: example\n"
            "issue:\n"
            "  id: 1\n"
            f"{'`' * backtick_count}\n"
        )

        result = try_fix_yaml(response_text, first_key="review", last_key="issue")

        assert result == {
            "review": {"summary": "example"},
            "issue": {"id": 1},
        }

    @pytest.mark.parametrize(
        "closing_fence",
        ["```yaml", "```yml", "```YAML", "```YML"],
    )
    def test_key_extraction_accepts_labeled_closing_fence(self, closing_fence):
        response_text = (
            "{\n"
            "Some garbage: [unclosed\n\n"
            "review:\n"
            "  summary: example\n"
            "issue:\n"
            "  id: 1\n"
            f"{closing_fence}\n"
        )

        result = try_fix_yaml(
            response_text,
            first_key="review",
            last_key="issue",
        )

        assert result == {
            "review": {"summary": "example"},
            "issue": {"id": 1},
        }


    # The YAML string is empty.
    def test_empty_yaml_fixed(self):
        review_text = ""
        assert try_fix_yaml(review_text) is None


    # The function extracts YAML snippet
    def test_no_initial_yaml(self):
        review_text = '''\
I suggest the following:

code_suggestions:
- relevant_file: |
    src/index.ts
  label: |
    best practice

- relevant_file: |
    src/index2.ts
  label: |
    enhancement
```

We can further improve the code by using the `const` keyword instead of `var` in the `src/index.ts` file.
'''
        expected_output = {'code_suggestions': [{'relevant_file': 'src/index.ts\n', 'label': 'best practice\n'}, {'relevant_file': 'src/index2.ts\n', 'label': 'enhancement'}]}

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='label') == expected_output

    def test_with_initial_yaml(self):
        review_text = '''\
I suggest the following:

```
code_suggestions:
- relevant_file: |
    src/index.ts
  label: |
    best practice

- relevant_file: |
    src/index2.ts
  label: |
    enhancement
```

We can further improve the code by using the `const` keyword instead of `var` in the `src/index.ts` file.
'''
        expected_output = {'code_suggestions': [{'relevant_file': 'src/index.ts\n', 'label': 'best practice\n'}, {'relevant_file': 'src/index2.ts\n', 'label': 'enhancement'}]}
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='label') == expected_output


    def test_with_brackets_yaml_content(self):
        review_text = '''\
{
code_suggestions:
- relevant_file: |
    src/index.ts
  label: |
    best practice

- relevant_file: |
    src/index2.ts
  label: |
    enhancement
}
'''
        expected_output = {'code_suggestions': [{'relevant_file': 'src/index.ts\n', 'label': 'best practice\n'}, {'relevant_file': 'src/index2.ts\n', 'label': 'enhancement'}]}
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='label') == expected_output

    def test_tab_indent_yaml(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    src/index.ts
  label: |
\tbest practice

- relevant_file: |
    src/index2.ts
  label: |
    enhancement
'''
        expected_output = {'code_suggestions': [{'relevant_file': 'src/index.ts\n', 'label': 'best practice\n'}, {'relevant_file': 'src/index2.ts\n', 'label': 'enhancement\n'}]}
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='label') == expected_output


    def test_leading_plus_mark_code(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    src/index.ts
  label: |
    best practice
  existing_code: |
+   var router = createBrowserRouter([
  improved_code: |
+   const router = createBrowserRouter([
'''
        expected_output = {'code_suggestions': [{
            'relevant_file': 'src/index.ts\n',
            'label': 'best practice\n',
            'existing_code': 'var router = createBrowserRouter([\n',
            'improved_code': 'const router = createBrowserRouter([\n'
        }]}
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='improved_code') == expected_output


    def test_inconsistent_indentation_in_block_scalar_yaml(self):
        """
            This test case represents a situation where the AI outputs the opening '{' with 5 spaces
            (resulting in an inferred indent level of 5), while the closing '}' is output with only 4 spaces.
            This inconsistency makes it impossible for the YAML parser to automatically determine the correct
            indent level, causing a parsing failure.

            The root cause may be the LLM miscounting spaces or misunderstanding the active block scalar context
            while generating YAML output.
        """

        review_text = '''\
code_suggestions:
- relevant_file: |
    tsconfig.json
  existing_code: |
     {
        "key1": "value1",
        "key2": {
          "subkey": "value"
         }
    }
'''
        expected_json = '''\
 {
    "key1": "value1",
    "key2": {
      "subkey": "value"
     }
}
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'tsconfig.json\n',
                'existing_code': expected_json
            }]
        }
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output


    def test_inconsistent_and_insufficient_indentation_in_block_scalar_yaml(self):
        """
            This test case reproduces a YAML parsing failure where the block scalar content
            generated by the AI includes inconsistent and insufficient indentation levels.

            The root cause may be the LLM miscounting spaces or misunderstanding the active block scalar context
            while generating YAML output.
        """

        review_text = '''\
code_suggestions:
- relevant_file: |
    tsconfig.json
  existing_code: |
    {
      "key1": "value1",
      "key2": {
        "subkey": "value"
      }
  }
'''
        expected_json = '''\
{
  "key1": "value1",
  "key2": {
    "subkey": "value"
  }
}
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'tsconfig.json\n',
                'existing_code': expected_json
            }]
        }
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output

    def test_stray_closing_brace_is_not_added_to_block_scalar(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    example.py
  improved_code: |
    return shared_helper(x)
  }
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'example.py\n',
                'improved_code': 'return shared_helper(x)\n'
            }]
        }

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='improved_code') == expected_output

    def test_stray_closing_brace_before_following_key_is_not_added_to_block_scalar(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    example.py
  improved_code: |
    return shared_helper(x)
  }
  label: |
    maintainability
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'example.py\n',
                'improved_code': 'return shared_helper(x)\n',
                'label': 'maintainability\n'
            }]
        }

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='improved_code') == expected_output

    def test_closing_brace_after_brace_in_string_stays_in_block_scalar(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    example.js
  existing_code: |
    if (x) {
      console.log("}");
  }
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'example.js\n',
                'existing_code': 'if (x) {\n  console.log("}");\n}\n'
            }]
        }

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output

    def test_closing_brace_after_else_block_stays_in_block_scalar(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    example.js
  existing_code: |
    } else {
      fallback()
  }
'''
        expected_output = {
            'code_suggestions': [{
                'relevant_file': 'example.js\n',
                'existing_code': '} else {\n  fallback()\n}\n'
            }]
        }

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output


    def test_wrong_indentation_code_block_scalar(self):
        review_text = '''\
code_suggestions:
- relevant_file: |
    a.c
  existing_code: |
  int sum(int a, int b) {
    return a + b;
  }

  int sub(int a, int b) {
    return a - b;
  }
'''
        expected_code_block = '''\
int sum(int a, int b) {
  return a + b;
}

int sub(int a, int b) {
  return a - b;
}
'''
        expected_output = {'code_suggestions': [{'relevant_file': 'a.c\n', 'existing_code': '  int sum(int a, int b) {\n    return a + b;\n  }\n\n  int sub(int a, int b) {\n    return a - b;\n  }\n'}]}
        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output

    def test_diff_markers_removed_within_list_item(self):
        """
            Ensures diff-style '-' markers nested inside list items are normalised so the YAML parses
            into the expected structure.
        """
        review_text = '''\
code_suggestions:
- relevant_file: |
    example.rb
  existing_code: |
+    puts 'hello'
+    puts 'world'
- relevant_file: |
-    example.py
-  existing_code: |
-+    print('hello')
-+    print('world')
'''
        expected_output = {
            'code_suggestions': [
                {
                    'relevant_file': 'example.rb\n',
                    'existing_code': "puts 'hello'\nputs 'world'\n"
                },
                {
                    'relevant_file': 'example.py\n',
                    'existing_code': "print('hello')\nprint('world')\n"
                }
            ]
        }

        assert try_fix_yaml(review_text, first_key='code_suggestions', last_key='existing_code') == expected_output

    def test_try_fix_yaml_fallbacks_do_not_log_success_on_none(self):
        # When all fallbacks produce None from yaml.safe_load (e.g. sanitized-to-empty input), no fallback
        # should log "Successfully parsed" — that would contradict the "Failed to parse" error that follows.
        captured = []
        sink_id = get_logger().add(lambda msg: captured.append(msg), level="INFO")
        try:
            result = load_yaml('\x08\x08\x08')
            assert result == {}
            assert not any("Successfully parsed" in m for m in captured)
            assert any("Failed to parse AI prediction after fallbacks" in m for m in captured)
        finally:
            get_logger().remove(sink_id)

    def test_diff_marker_fallback_does_not_log_success_on_none(self):
        # This input reaches the diff-marker fallback and still parses to None, unlike the
        # '\x08\x08\x08' case above, which never enters that branch at all.
        captured = []
        sink_id = get_logger().add(lambda msg: captured.append(msg), level="INFO")
        try:
            result = load_yaml('-\n-#x')
            assert result == {}
            assert not any("normalizing diff removal markers" in m for m in captured)
            assert any("Failed to parse AI prediction after fallbacks" in m for m in captured)
        finally:
            get_logger().remove(sink_id)
